# Generated by Django 5.0.1 on 2025-10-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last sync with WooCommerce",
                null=True,
                verbose_name="Last Synced At",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="woocommerce_product_id",
            field=models.IntegerField(
                blank=True,
                help_text="WooCommerce product ID for sync",
                null=True,
                verbose_name="WooCommerce Product ID",
            ),
        ),
    ]
