# Generated by Django 5.0.1 on 2025-10-25 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_onboarding_completed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("customers", "Customers"),
                            ("orders", "Orders"),
                            ("products", "Products"),
                            ("coupons", "Coupons"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("import", "Import from WooCommerce"),
                            ("export", "Export to WooCommerce"),
                            ("bidirectional", "Bi-directional Sync"),
                        ],
                        default="import",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_items", models.IntegerField(default=0)),
                ("processed_items", models.IntegerField(default=0)),
                ("successful_items", models.IntegerField(default=0)),
                ("failed_items", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_sync_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Job",
                "verbose_name_plural": "Sync Jobs",
                "db_table": "integrations_sync_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "item_id",
                    models.CharField(
                        blank=True,
                        help_text="WooCommerce or local item ID",
                        max_length=255,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "sync_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="integrations.syncjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "db_table": "integrations_sync_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="WooCommerce event type (e.g., customer.created)",
                        max_length=100,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Resource type (customer, order, product, coupon)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        help_text="WooCommerce resource ID", max_length=100
                    ),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full webhook payload"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("signature", models.CharField(blank=True, max_length=255)),
                ("signature_verified", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "integrations_webhook_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WooCommerceConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "store_url",
                    models.URLField(
                        help_text="WooCommerce store URL (e.g., https://example.com)",
                        max_length=500,
                    ),
                ),
                (
                    "consumer_key",
                    models.CharField(
                        help_text="WooCommerce REST API Consumer Key", max_length=255
                    ),
                ),
                (
                    "consumer_secret",
                    models.CharField(
                        help_text="WooCommerce REST API Consumer Secret", max_length=255
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for verifying webhook signatures",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether this connection is active"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful sync timestamp",
                        null=True,
                    ),
                ),
                ("sync_customers", models.BooleanField(default=True)),
                ("sync_orders", models.BooleanField(default=True)),
                ("sync_products", models.BooleanField(default=True)),
                ("sync_coupons", models.BooleanField(default=True)),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic periodic sync"
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Sync interval in minutes (if auto-sync enabled)",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="woocommerce_connection",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "WooCommerce Connection",
                "verbose_name_plural": "WooCommerce Connections",
                "db_table": "integrations_woocommerce_connection",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Coupon code (unique per tenant)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Internal description of the coupon"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage Discount"),
                            ("fixed_cart", "Fixed Cart Discount"),
                            ("fixed_product", "Fixed Product Discount"),
                        ],
                        default="percent",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount amount (percentage or fixed)",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum cart amount required",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "maximum_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum cart amount allowed",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "individual_use",
                    models.BooleanField(
                        default=False, help_text="Cannot be used with other coupons"
                    ),
                ),
                (
                    "exclude_sale_items",
                    models.BooleanField(
                        default=False, help_text="Exclude items on sale"
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times coupon can be used",
                        null=True,
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.IntegerField(
                        blank=True, help_text="Maximum uses per customer", null=True
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, help_text="Number of times used"),
                ),
                (
                    "date_expires",
                    models.DateTimeField(
                        blank=True, help_text="Coupon expiration date", null=True
                    ),
                ),
                (
                    "product_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="WooCommerce product IDs this coupon applies to",
                    ),
                ),
                (
                    "excluded_product_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="WooCommerce product IDs excluded from coupon",
                    ),
                ),
                (
                    "product_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category IDs this coupon applies to",
                    ),
                ),
                (
                    "excluded_product_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Category IDs excluded from coupon",
                    ),
                ),
                (
                    "email_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Email addresses that can use this coupon",
                    ),
                ),
                (
                    "woocommerce_coupon_id",
                    models.IntegerField(
                        blank=True, help_text="WooCommerce coupon ID", null=True
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Last sync with WooCommerce", null=True
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending Sync"),
                            ("error", "Sync Error"),
                            ("not_synced", "Not Synced"),
                        ],
                        default="not_synced",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether coupon is active"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "db_table": "integrations_coupon",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "code")},
            },
        ),
    ]
