# Generated by Django 5.0.1 on 2025-10-17 18:27

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('business_name', models.CharField(help_text='Name of the business or clinic', max_length=255, verbose_name='Business Name')),
                ('owner_email', models.EmailField(help_text='Email address of the business owner', max_length=254, unique=True, verbose_name='Owner Email')),
                ('owner_phone', models.CharField(help_text='Phone number of the business owner', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Owner Phone')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the phone number has been verified via SMS', verbose_name='Phone Verified')),
                ('logo', models.ImageField(blank=True, help_text='Logo of the business (optional)', null=True, upload_to='tenant_logos/', verbose_name='Business Logo')),
                ('plan', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Pro')], default='BASIC', help_text='Current subscription plan', max_length=10, verbose_name='Subscription Plan')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('subscription_expires_at', models.DateTimeField(blank=True, help_text='When the current subscription expires', null=True, verbose_name='Subscription Expires At')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant account is active', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_email'], name='accounts_te_owner_e_371d44_idx'), models.Index(fields=['is_active', 'plan'], name='accounts_te_is_acti_a009c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('email', models.EmailField(help_text='Email address (used for login)', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the phone number has been verified via SMS', verbose_name='Phone Verified')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('BASIC_STAFF', 'Basic Staff')], default='BASIC_STAFF', help_text='User role (Admin or Basic Staff)', max_length=20, verbose_name='Role')),
                ('google_sub', models.CharField(blank=True, help_text='Google OAuth subject identifier', max_length=255, null=True, unique=True, verbose_name='Google Subject ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, help_text='The tenant (business) this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'), models.Index(fields=['tenant', 'is_active'], name='accounts_us_tenant__78e6c9_idx'), models.Index(fields=['google_sub'], name='accounts_us_google__3a6c13_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
