# Generated by Django 5.0.1 on 2025-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed the onboarding process",
                verbose_name="Onboarding Completed",
            ),
        ),
    ]
