# Generated by Django 5.0.1 on 2025-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="account_status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("LOCKED_BASIC", "Locked - Over Limit")],
                default="ACTIVE",
                help_text="Account status (ACTIVE or LOCKED_BASIC if over limits)",
                max_length=20,
                verbose_name="Account Status",
            ),
        ),
    ]
