# Generated by Django 5.0.1 on 2026-01-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_tenant_account_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
    ]
