# Generated by Django 5.0.1 on 2026-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_tenant_is_deleted_user_is_deleted"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_uid",
            field=models.CharField(
                blank=True,
                help_text="Supabase Auth user identifier (UUID)",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Supabase User ID",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["supabase_uid"], name="accounts_us_supabas_ebc054_idx"
            ),
        ),
    ]
