# Generated by Django 5.0.1 on 2025-10-24 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_onboarding_completed"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("WOOCOMMERCE", "WooCommerce"),
                            ("SHOPIFY", "Shopify"),
                        ],
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                (
                    "store_url",
                    models.URLField(
                        help_text="e.g., https://mystore.com", verbose_name="Store URL"
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "api_secret",
                    models.CharField(
                        blank=True,
                        help_text="Required for some platforms",
                        max_length=255,
                        verbose_name="API Secret",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "auto_sync_customers",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically import new customers",
                        verbose_name="Auto Sync Customers",
                    ),
                ),
                (
                    "auto_sync_orders",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically import new orders",
                        verbose_name="Auto Sync Orders",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Sync At"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_integrations",
                        to="accounts.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "אינטגרציית פלטפורמה",
                "verbose_name_plural": "אינטגרציות פלטפורמה",
            },
        ),
        migrations.CreateModel(
            name="ImportedCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Customer ID in the external platform",
                        max_length=100,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "external_data",
                    models.JSONField(
                        default=dict,
                        help_text="Raw data from external platform",
                        verbose_name="External Data",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Imported At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_customers",
                        to="customers.platformintegration",
                        verbose_name="Integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "לקוח מיובא",
                "verbose_name_plural": "לקוחות מיובאים",
            },
        ),
        migrations.AddIndex(
            model_name="platformintegration",
            index=models.Index(
                fields=["tenant", "is_active"], name="customers_p_tenant__bec50e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="platformintegration",
            unique_together={("tenant", "platform", "store_url")},
        ),
        migrations.AddIndex(
            model_name="importedcustomer",
            index=models.Index(
                fields=["integration", "external_id"],
                name="customers_i_integra_2c38a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importedcustomer",
            index=models.Index(
                fields=["customer"], name="customers_i_custome_3cfdde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importedcustomer",
            unique_together={("integration", "external_id")},
        ),
    ]
