# Generated by Django 5.0.1 on 2025-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_platformintegration_importedcustomer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[
                    ("PRIVATE", "Private Customer"),
                    ("BUSINESS", "Business Customer"),
                    ("TREATMENT", "Treatment Customer"),
                    ("VIP", "VIP"),
                ],
                default="PRIVATE",
                max_length=20,
                verbose_name="Customer Type",
            ),
        ),
    ]
