# Generated by Django 5.0.1 on 2025-10-25 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_onboarding_completed"),
        ("customers", "0003_alter_customer_customer_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Full Name"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g., קוסמטיקאית, מטפלת בייזר",
                        max_length=100,
                        verbose_name="Role",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "מטפל/ת",
                "verbose_name_plural": "מטפלים",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "treatment_name",
                    models.CharField(
                        help_text="Snapshot of treatment name at time of treatment",
                        max_length=255,
                        verbose_name="Treatment Name",
                    ),
                ),
                ("treatment_date", models.DateField(verbose_name="Treatment Date")),
                (
                    "staff_member_name",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of staff member name at time of treatment",
                        max_length=255,
                        verbose_name="Staff Member Name",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Treatment notes, observations, recommendations",
                        verbose_name="Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "טיפול",
                "verbose_name_plural": "טיפולים",
                "ordering": ["-treatment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., טיפול פנים, לייזר שיער",
                        max_length=255,
                        verbose_name="Treatment Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default price for this treatment",
                        max_digits=10,
                        null=True,
                        verbose_name="Default Price",
                    ),
                ),
                (
                    "default_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration for scheduling",
                        null=True,
                        verbose_name="Default Duration (minutes)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "סוג טיפול",
                "verbose_name_plural": "סוגי טיפולים",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Used for birthday marketing campaigns",
                null=True,
                verbose_name="Birth Date",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_purchase_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Purchase Date"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last sync with WooCommerce",
                null=True,
                verbose_name="Last Synced At",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_treatment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Treatment Date"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="medical_notes",
            field=models.TextField(
                blank=True,
                help_text="Allergies, medical conditions, etc.",
                verbose_name="Medical Notes",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom preferences (skin type, preferred products, etc.)",
                verbose_name="Preferences",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Customer profile picture (PRO+ feature)",
                null=True,
                upload_to="customer_profiles/",
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="purchase_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of product purchases",
                verbose_name="Purchase Count",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_purchases",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total spent on products",
                max_digits=12,
                verbose_name="Total Purchases",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_treatments",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total spent on treatments",
                max_digits=12,
                verbose_name="Total Treatments",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="treatment_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of treatments",
                verbose_name="Treatment Count",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="woocommerce_customer_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="WooCommerce Customer ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_order_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Order Date (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="General customer notes and preferences",
                verbose_name="General Notes",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_orders",
            field=models.IntegerField(default=0, verbose_name="Total Orders (Legacy)"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Total Spent (Legacy)",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["woocommerce_customer_id"],
                name="customers_c_woocomm_aa3300_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["birth_date"], name="customers_c_birth_d_0375e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone"), name="unique_phone_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("tenant", "email"),
                name="unique_email_per_tenant",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="accounts.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_treatments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="customers.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="customers.staffmember",
                verbose_name="Staff Member",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="accounts.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="treatmenttype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_types",
                to="accounts.tenant",
                verbose_name="Tenant",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="treatment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="customers.treatmenttype",
                verbose_name="Treatment Type",
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["tenant", "is_active"], name="customers_s_tenant__e56792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmenttype",
            index=models.Index(
                fields=["tenant", "is_active"], name="customers_t_tenant__186521_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmenttype",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="unique_treatment_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["tenant", "-treatment_date"],
                name="customers_t_tenant__364270_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["customer", "-treatment_date"],
                name="customers_t_custome_c7a061_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["treatment_type"], name="customers_t_treatme_940cbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["staff_member"], name="customers_t_staff_m_c03f71_idx"
            ),
        ),
    ]
